name: my-test-workflow
run-name: ${{ github.actor }} is testing GitHub
on:
  push:
    branches: [ main ]
jobs:
  test-node-js:
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        node-version: '14.x'
      - run: npm install
      - run: npm test


  